src/Entity/Campaign.php
<?php

namespace App\Entity;

use App\Repository\CampaignRepository;
use DateInterval;
use DateInvalidTimeZoneException;
use DateTimeInterface;
use DateTimeZone;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CampaignRepository::class)]
class Campaign
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 65535)]
    private ?string $template = null;

    #[ORM\Column(type: 'string', enumType: State::class)]
    public State $state = State::Pending;

    #[ORM\ManyToOne(inversedBy: 'campaigns')]
    #[ORM\JoinColumn(nullable: false)]
    private ?SendingList $sendingList = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $name = null;

    #[ORM\Column(type: Types::DATETIMETZ_MUTABLE)]
    private ?DateTimeInterface $dateStart = null;

    #[ORM\Column(type: Types::DATETIMETZ_MUTABLE)]
    private ?DateTimeInterface $dateEnd = null;

    #[ORM\Column]
    private ?int $cursor = 0;

    #[ORM\Column(length: 255)]
    private ?string $timezone = null;

    public function __construct()
    {
        $this->cursor = 0;
        $this->dateStart = new \DateTimeImmutable();
        $this->dateStart->setTime(9,0);

        $this->dateEnd = new \DateTimeImmutable();
        $this->dateEnd = $this->dateEnd->add(new DateInterval('P7D'));
        $this->dateEnd->setTime(20, 0, 0);
    }


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTemplate(): ?string
    {
        return $this->template;
    }

    public function setTemplate(string $template): static
    {
        $this->template = $template;

        // Reset cursor
        if($this->state === State::Pending || $this->state === State::Launched) {
            $this->setCursor(0);
        }

        return $this;
    }

    public function getSendingList(): ?SendingList
    {
        return $this->sendingList;
    }

    public function setSendingList(?SendingList $sendingList): static
    {
        $this->sendingList = $sendingList;
        // Reset cursor
        if($this->state === State::Pending || $this->state === State::Launched) {
            $this->setCursor(0);
        }

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(?string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getState(): State
    {
        return $this->state;
    }

    public function setState(State $state): void
    {
        $this->state = $state;
    }

    /**
     */
    public function getDateStart(): ?DateTimeInterface
    {
        return $this->dateStart;
    }

    /**
     * @throws DateInvalidTimeZoneException
     */
    public function getDateStartTimezone(): ?DateTimeInterface
    {
        $realDate = clone $this->dateStart;
        $realDate->setTimezone(new DateTimeZone($this->timezone));
        $realDate->setTime($this->dateStart->format('H'), $this->dateStart->format('i'), 0);

        return $realDate;
    }


    public function setDateStart(DateTimeInterface $dateStart): static
    {
        $this->dateStart = $dateStart;

        return $this;
    }

    /**
     * @throws DateInvalidTimeZoneException
     */
    public function getDateEnd(): ?DateTimeInterface
    {
        return $this->dateEnd;
    }

    /**
     * @throws DateInvalidTimeZoneException
     */
    public function getDateEndTimezone(): ?DateTimeInterface
    {
        $realDate = clone $this->dateEnd;
        $realDate->setTimezone(new DateTimeZone($this->timezone));
        $realDate->setTime($this->dateEnd->format('H'), $this->dateEnd->format('i'), 0);

        return $realDate;
    }

    public function setDateEnd(DateTimeInterface $dateEnd): static
    {
        $this->dateEnd = $dateEnd;

        return $this;
    }

    public function getCursor(): ?int
    {
        return $this->cursor;
    }

    public function setCursor(int $cursor): static
    {
        $this->cursor = $cursor;

        return $this;
    }

    public function getTimezone(): ?string
    {
        return $this->timezone;
    }

    public function setTimezone(string $timezone): static
    {
        $this->timezone = $timezone;

        return $this;
    }
}

src/Controller/CampaignController.php
<?php

namespace App\Controller;

use App\Entity\Campaign;
use App\Form\CampaignOneType;
use App\Form\CampaignTwoType;
use App\Repository\CampaignRepository;
use App\Repository\SendingListRepository;
use App\Service\ServiceCampaign;
use App\Service\ServiceCSV;
use App\Service\ServiceSendingList;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\RequestStack;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
use Symfony\Component\Routing\Attribute\Route;

class CampaignController extends AbstractController
{
    public function __construct(
        private readonly RequestStack $requestStack,
    )
    {
    }

    #[Route('/campaign', name: 'campaign')]
    public function index(CampaignRepository $repository, ServiceCampaign $serviceCampaign): Response
    {
        $campaigns = $repository->findAll();
        $metadata = [];
        foreach ($campaigns as $campaign) {
            $metadata[$campaign->getId()] = $serviceCampaign->getCampaignMetadata($campaign);
        }

        return $this->render('campaign/index.html.twig', [
            'controller_name' => 'CampaignController',
            'campaigns' => $repository->findAll(),
            'metadata' => $metadata,
        ]);
    }

    #[Route('/campaign/{id}/view', name: 'campaign_view')]
    public function view($id, CampaignRepository $repository, ServiceCampaign $serviceCampaign, ServiceCSV $serviceCSV): Response
    {
        $campaign = $repository->find($id);
        $file = $campaign->getSendingList()->getFile();
        $columns = $file ? $serviceCSV->getColumns($file->getContent()) : [];

        return $this->render('campaign/view.html.twig', [
            'controller_name' => 'CampaignController',
            'entry' => $campaign,
            'columns' => $columns,
            'metadata' => $serviceCampaign->getCampaignMetadata($campaign),
        ]);
    }

    #[Route('/campaign/{id}/edit/stage-one', name: 'campaign_edit_one', methods: ['GET', 'POST'])]
    public function edit($id, Request $request, CampaignRepository $repo, ServiceCSV $serviceCSV): Response
    {
        if($id === "new") {
            $campaign = new Campaign();
        }
        else if(is_numeric($id)) {
            $campaign = $repo->find($id);
        }
        else {
            throw new NotFoundHttpException();
        }

        $form = $this->createForm(CampaignOneType::class, $campaign);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->requestStack->getSession()->set('campaign-form-stage-one', $form->getData());
            return $this->redirectToRoute('campaign_edit_two');
        }

        return $this->render('campaign/new-one.html.twig', [
            'form' => $form,
            'entry' => $campaign
        ]);
    }

    #[Route('/campaign/edit/stage-two', name: 'campaign_edit_two', methods: ['GET', 'POST'])]
    public function edit_two(Request $request, CampaignRepository $campaignRepository,
                             EntityManagerInterface $entityManager, SendingListRepository $sendingListRepository,
                             ServiceCSV $serviceCSV, ServiceSendingList $serviceSendingList): Response
    {
        /** @var Campaign $campaign */
        $sessionCampaign = $this->requestStack->getSession()->get('campaign-form-stage-one');
        $campaign = $sessionCampaign;

        if(!$sessionCampaign) return $this->redirectToRoute('campaign');
        if($sessionCampaign->getId()) $campaign = $campaignRepository->find($sessionCampaign->getId());

        $realSendingList = $sendingListRepository->find($sessionCampaign->getSendingList()->getId());
        $campaign->setSendingList($realSendingList);

        $form = $this->createForm(CampaignTwoType::class, $campaign);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $campaign->setSendingList($realSendingList);
            $entityManager->persist($campaign);
            $entityManager->flush();

            return $this->redirectToRoute('campaign');
        }

        $file = $serviceSendingList->getFile($realSendingList);
        $columns = $file ? $serviceCSV->getColumns($file->getContent()) : [];

        return $this->render('campaign/new-two.html.twig', [
            'form' => $form,
            'entry' => $campaign,
            'columns' => $columns
        ]);
    }

    #[Route('/campaign/{id}/delete', name: 'campaign_delete', methods: ['GET'])]
    public function delete(Campaign $campaign, EntityManagerInterface $entityManager): Response
    {
        $entityManager->remove($campaign);
        $entityManager->flush();

        return $this->redirectToRoute('campaign');
    }
}

templates/campaign/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Sending list{% endblock %}

{% block javascripts %}
    {{ parent() }}
    <script src="{{ asset('script/campaign/script.js') }}"></script>
{% endblock %}

{% block stylesheets %}
    {{ parent() }}
{% endblock %}

{% block body %}
    {{ parent() }}
    <div class="flex justify-between items-center mb-5">
        <h1 class="h1">Campaigns</h1>
        <a class="btn btn-success h-10" href="{{ path('campaign_edit_one', { 'id': 'new' }) }}">Create</a>
    </div>

    {% for entry in campaigns %}
        {% set cursor = metadata[entry.id].cursor %}
        {% if cursor < 0 %} {% set cursor = 0 %} {% endif %}

        <a href="{{ path('campaign_view', {'id': entry.id}) }}" class="flex justify-between p-3 bg-gray-100 border-slate-100 border rounded-md mb-3">
            <div class="w-full flex flex-column justify-between mr-2">
                <p class="h3 text-slate-800 mb-2">{{ entry.name }}</p>

                <div class="flex justify-between items-center w-full">
                    <div class="">
                        <span>State : </span>
                        <span class="text-slate-800 {% if entry.state.value == 'pending' %} !text-yellow-500
                                                {% elseif entry.state.value == 'cancelled' %} !text-red-500
                                                {% elseif entry.state.value == 'finished' %} !text-green-500
                                                {% elseif entry.state.value == 'launched' %} !text-blue-500 {% endif %}">
                            {{ entry.state.value }}
                        </span>
                    </div>
                </div>

            </div>
            <div class="flex flex-col items-end w-max min-w-max">
                <button data-href="{{ path('campaign_delete', { 'id': entry.id }) }}"
                        class="btn btn-danger h-10 btn-delete mb-2">
                    {{ ux_icon('ion:trash-outline', {class: 'w-4 h-4'}) }}
                </button>
                <div>
                    {{ cursor }} / {{ metadata[entry.id].total }}
                </div>
            </div>
        </a>
    {% endfor %}
{% endblock %}

templates/campaign/new-one.html.twig
{% form_theme form 'bootstrap_5_layout.html.twig' %}
{% extends 'base.html.twig' %}

{% block title %}Edit campaign - {{ entry.name }}{% endblock %}

{% block javascripts %}
    {{ parent() }}
{% endblock %}

{% block stylesheets %}
    {{ parent() }}
{% endblock %}

{% block body %}
    {{ parent() }}
    <h1 class="h1 mb-6">{% if entry.id and entry.name %}Edit campaign - {{ entry.name }} {% else %} Create campaign {% endif %}</h1>

    {{ form_start(form, {'attr': {'novalidate': 'novalidate'}}) }}
        {{ form_label(form.sendingList) }}
        <div class="flex justify-between items-center mb-3">
            {{ form_widget(form.sendingList, { 'attr': { 'class': 'w-full mr-2' } }) }}
            <a class="btn btn-success w-10" href="{{ path('sending_list_edit', {'id': 'new'}) }}">Add</a>
        </div>
        {{ form_row(form.submit) }}
    {{ form_end(form) }}
{% endblock %}

templates/campaign/new-two.html.twig
{% form_theme form 'bootstrap_5_layout.html.twig' %}
{% extends 'base.html.twig' %}

{% block title %}Edit campaign - {{ entry.name }}{% endblock %}

{% block javascripts %}
    {{ parent() }}
{% endblock %}

{% block stylesheets %}
    {{ parent() }}
{% endblock %}

{% block body %}
    {{ parent() }}
    <h1 class="h1 mb-6">{% if entry.id and entry.name %}Edit campaign - {{ entry.name }} {% else %} Create campaign {% endif %}</h1>

    {{ form_start(form, {'attr': {'novalidate': 'novalidate'}}) }}
        {{ form_row(form.name) }}
        {{ form_row(form.template) }}
        <div class="flex -mt-2">
            <span class="text-slate-500 text-sm block mr-1 text-right w-full">Usable keywords : </span>
            {% for col in columns %}
                <span class="text-slate-500 text-sm block mr-2"> {{ '{{' ~ col ~ '}}' }}</span>
            {% endfor %}
        </div>

        <div class="flex">
            {{ form_row(form.state) }}
        </div>

        <div class="mb-6">
            {{ form_row(form.dateStart) }}
            {{ form_row(form.dateEnd) }}
            {{ form_row(form.timezone) }}
        </div>

        {{ form_row(form.submit) }}
    {{ form_end(form) }}
{% endblock %}

templates/campaign/view.html.twig
{% extends 'base.html.twig' %}
{% from 'macros.html.twig' import bytesToSize %}

{% block title %}Campaign - {{ entry.name }}{% endblock %}

{% block javascripts %}
    {{ parent() }}
{% endblock %}

{% block stylesheets %}
    {{ parent() }}
{% endblock %}

{% block body %}
    {{ parent() }}

    <div class="flex justify-between mb-6">
        <h1 class="h1">{% if entry.id and entry.name %}Campaign - {{ entry.name }} {% endif %}</h1>
        <a href="{{ path('campaign_edit_one', {'id': entry.id}) }}" class="btn pb-0 h-10 btn-primary">Edit</a>
    </div>

    <h1 class="h3 mb-3">Sending list</h1>
    <div class="flex justify-between p-3 bg-gray-100 border-slate-100 border rounded-md mb-6">
        {{ entry.sendingList.name }}
    </div>

    <h1 class="h3 mb-3">Template</h1>
    <div class="flex justify-between p-3 bg-gray-100 border-slate-100 border rounded-md mb-6">
        {{ entry.template }}
        {% if entry.template is null %}No template defined{% endif %}
    </div>

    <h1 class="h3">State</h1>
    <div class="mb-3">
        <span class="text-slate-800 {% if entry.state.value == 'pending' %} !text-yellow-500
                                            {% elseif entry.state.value == 'cancelled' %} !text-red-500
                                            {% elseif entry.state.value == 'finished' %} !text-green-500
                                            {% elseif entry.state.value == 'launched' %} !text-blue-500 {% endif %}">
                    {{ entry.state.value }}
        </span>
    </div>

    <h1 class="h3">Clients covered</h1>
    <div class="mb-3">
        {% set cursor = metadata.cursor %}
        {% if cursor < 0 %} {% set cursor = 0 %} {% endif %}
        <div>Sent <span class="text-yellow-600">{{ cursor }}</span></div>
        <div>from total <span class="text-blue-500">{{ metadata.total }}</span></div>
    </div>

    <h1 class="h3 mb-3">Dates</h1>
    <div class="flex flex-col justify-between w-1/2 p-3 bg-gray-100 border-slate-100 border rounded-md mb-6">
        <div class="grid grid-cols-2 col-span-3 mb-2 border border-slate-100 rounded-md bg-gray-50 px-3 py-2">
            <div>Start</div>
            <div class="flex justify-end text-blue-500">{{ entry.dateStartTimezone|date("F d, Y - h:i", entry.timezone) }}</div>
        </div>
        <div class="grid grid-cols-2 col-span-3 mb-2 border border-slate-100 rounded-md bg-gray-50 px-3 py-2">
            <div>End</div>
            <div class="flex justify-end text-blue-500">{{ entry.dateEndTimezone|date("F d, Y - H:i", entry.timezone) }}</div>
        </div>
        <div class="grid grid-cols-2 col-span-3 mb-2 border border-slate-100 rounded-md bg-gray-50 px-3 py-2">
            <div>Time zone</div>
            <div class="flex justify-end text-blue-500">{{ entry.timeZone|timezone_name}}</div>
        </div>
    </div>

    <h1 class="h3 mb-3">Schedule</h1>
    <div class="flex flex-col justify-between p-3 bg-gray-100 border-slate-100 border rounded-md mb-6 w-1/2">
        {% for date in metadata.dates %}
            <div class="grid grid-cols-2 col-span-3 mb-2 border border-slate-100 rounded-md bg-gray-50 px-3 py-1 {% if date.passed %} !bg-amber-50 {% endif %}">
                <div>Date</div>
                <div class="flex justify-end">{{ date.date|date("F d, Y - H:i", entry.timezone) }}</div>
                <div>Clients covered</div>
                <div class="flex justify-end">{{ date.cursor }} / {{ metadata.total }}</div>
            </div>
        {% endfor %}
    </div>



{% endblock %}